language: node_js
script:
- npm test
deploy:
  api_key:
    secure: JHk1shYOhWTUq9Fu00SXqN6eaV30OWKXifSfXknTKbvGxoTROKecH1X9WYVKKTUWNnU9pYkYJfiAsnTWI4+qYOr5kOYpB0WycObSe6R3vvQ5PAHPJbQJqIpZFWYUkXnp5PEfi1TgS1BWBNBkFE8ylavL3nCu5gjWNJqqnQ1AYNEUOb+sqmC4tic5n6QNrWgNg899zKDmpHYVRmHce37ydI4OlHN4DCIej6UXMQ4C/0AmF1CLQ4jWvkWCn3g+O6m/xhhhD0HEVR6NEeWzwJ/tSwPRy85ANp8/kw5trn+x1ZD19ZpeIDPB+/ervbAz/6TRDEDGGn8AiJ3zA7ZRd4IJSabTNf8QwvT/+WQRRN2Dab2XgqZh+FuxPWjQVhjgaR8DUvXV5gVup7rP7d0V+9PO0MUeK9yCl3RUJTQWixfGrkbbyRQuiaUg1f8MmbuRh7HBQ2o6Q8XdoLYs6fFsNrzb2jqYQ6OCHCzq4Vf/b3Ngsi/nt9m/cuovc3/ezkNhO0Om6lqiHMFE+UQwS+sSNa/tgwLMdtSTUY43aRsuDZZGSUOb59cuCCFDd1SWvPXCCKwwQbMP1VzjfA4kj8RgBUlPTAcna3cuLExPGl1/OV2XqWPCfmwFvTCIparDlIhF4cQKpemQCpq34+h3L2HGUqPDo3E9VfGSSlQeAYYJAHoyl/4=
